# Generated by Django 6.1.2 on 2026-10-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ship_mode', models.CharField(max_length=32)),
                ('segment', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=64)),
                ('sub_category', models.CharField(max_length=64)),
                ('sales_category', models.CharField(max_length=32)),
                ('sales', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
                ('log_sales', models.FloatField()),
                ('sales_per_quantity', models.FloatField()),
                ('discount_tier', models.CharField(max_length=32)),
                ('region_category_interaction', models.CharField(max_length=128)),
                ('churn_prediction', models.IntegerField(help_text='0 for Retained, 1 for Churned')),
                ('churn_probability', models.FloatField(help_text='Predicted probability between 0.0 and 1.0')),
                ('risk_tier', models.CharField(choices=[('Low', 'Low Risk (< 25%)'), ('Medium', 'Medium Risk (25% - 50%)'), ('High', 'High Risk (> 50%)')], default='Low', max_length=16)),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('model_version', models.CharField(default='v1.0-pre-release', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Customer Prediction Record',
                'verbose_name_plural': 'Customer Prediction Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
